#ifndef TURBO_FLOW_APPLICANT_MAPPER_PLUGIN_H
#define TURBO_FLOW_APPLICANT_MAPPER_PLUGIN_H

#include <stdint.h>

#define TURBO_FLOW_APPLICANT_MAPPER_PLUGIN_ID "applicant.mapper"
#define TURBO_FLOW_APPLICANT_MAPPER_PLUGIN_VERSION "1.0.0"
#define TURBO_FLOW_APPLICANT_MAPPER_NAME "applicant-json"
#define TURBO_FLOW_APPLICANT_MAPPER_PROFILE "applicant-json"
#define TURBO_FLOW_APPLICANT_SCHEMA_ID "rulesforge.Applicant.data"
#define TURBO_FLOW_APPLICANT_TYPE_NAME "Applicant"
#define TURBO_FLOW_APPLICANT_SCHEMA_VERSION UINT32_C(1)
#define TURBO_FLOW_APPLICANT_COAP_MESSAGE_TYPE UINT32_C(2)
#define TURBO_FLOW_APPLICANT_COAP_SEMANTIC_TYPE UINT32_C(50)
#define TURBO_FLOW_APPLICANT_JTT808_MESSAGE_TYPE UINT32_C(0x0900)
#define TURBO_FLOW_APPLICANT_JTT808_SEMANTIC_TYPE UINT32_C(1)
#define TURBO_FLOW_APPLICANT_MAPPER_MAX_BYTES 4096u

#endif /* TURBO_FLOW_APPLICANT_MAPPER_PLUGIN_H */
