#ifndef TURBO_FLOW_CONFIG_LIMITS_H
#define TURBO_FLOW_CONFIG_LIMITS_H

/* Shared resolver/runtime contract; keep one source of truth for admission bounds. */
#define TURBO_FLOW_CONFIG_INGRESS_DEFAULT_WORKERS 1u
#define TURBO_FLOW_CONFIG_INGRESS_DEFAULT_CAPACITY 1024u
#define TURBO_FLOW_CONFIG_INGRESS_MAX_WORKERS 256u
#define TURBO_FLOW_CONFIG_INGRESS_MAX_CAPACITY 1048576u

#endif /* TURBO_FLOW_CONFIG_LIMITS_H */
