function(chttp_require_native_abi dependencies)
  string(REGEX MATCHALL "(^|[\r\n])[ \t]*salts_chttp[^ \t\r\n]*" imports "${dependencies}")
  list(LENGTH imports count)
  if(count EQUAL 1)
    list(GET imports 0 native_import)
    string(STRIP "${native_import}" native_import)
  endif()
  if(NOT count EQUAL 1 OR NOT native_import STREQUAL "salts_chttp-2.dll")
    message(FATAL_ERROR "CHTTP requires salts_chttp-2.dll")
  endif()
endfunction()

if(DEFINED CHTTP_TEST_DEPENDENCY)
  chttp_require_native_abi("    ${CHTTP_TEST_DEPENDENCY}\n")
endif()
