#ifndef CHTTP_PLUGIN_FIXTURES_H
#define CHTTP_PLUGIN_FIXTURES_H
#if defined(_WIN32)
  #define CHTTP_TEST_BACKEND "iocp"
#elif defined(__APPLE__)
  #define CHTTP_TEST_BACKEND "kqueue"
#else
  #define CHTTP_TEST_BACKEND "epoll"
#endif
static const char client_yaml[] = "version: 1\n"
                                  "adapters:\n"
                                  "  client:\n"
                                  "    kind: chttp.client\n"
                                  "    config:\n"
                                  "      schema_version: 1\n"
                                  "      poll_budget_ms: 1\n"
                                  "      tls_enabled: false\n"
                                  "      backend: " CHTTP_TEST_BACKEND "\n"
                                  "      network_connection_capacity: 4\n"
                                  "      network_command_capacity: 16\n"
                                  "      network_request_capacity: 16\n"
                                  "      network_completion_batch_capacity: 16\n"
                                  "      network_event_capacity: 16\n"
                                  "      network_max_send_bytes: 65536\n"
                                  "      network_receive_buffer_bytes: 4096\n"
                                  "      network_command_buffer_bytes: 131072\n"
                                  "      network_event_buffer_bytes: 65536\n"
                                  "      network_connect_timeout_ms: 1000\n"
                                  "      network_read_timeout_ms: 1000\n"
                                  "      network_write_timeout_ms: 1000\n"
                                  "      network_tls_handshake_timeout_ms: 0\n"
                                  "      network_tls_io_buffer_bytes: 0\n"
                                  "      tls_ca_file: \"\"\n"
                                  "      tls_ca_path: \"\"\n"
                                  "      tls_cert_file: \"\"\n"
                                  "      tls_key_file: \"\"\n"
                                  "      tls_key_password: \"\"\n"
                                  "      tls_alpn: []\n"
                                  "      protocol: \"h1\"\n"
                                  "      connection_uri: \"tcp://127.0.0.1:9\"\n"
                                  "      authority: \"127.0.0.1\"\n"
                                  "      target: \"/echo\"\n"
                                  "      method: \"POST\"\n"
                                  "      tls_server_name: \"\"\n"
                                  "      request_capacity: 4\n"
                                  "      max_start_line_bytes: 256\n"
                                  "      max_header_count: 16\n"
                                  "      max_header_bytes: 1024\n"
                                  "      max_request_body_bytes: 512\n"
                                  "      max_response_body_bytes: 512\n"
                                  "      max_informational_responses: 2\n"
                                  "      stream_chunk_bytes: 512\n"
                                  "      h2_input_buffer_bytes: 65536\n"
                                  "      h2_hpack_dynamic_table_bytes: 4096\n"
                                  "      h2_max_settings_count: 16\n"
                                  "      overall_timeout_ms: 1000\n"
                                  "      retry_delay_ms: 0\n"
                                  "      max_attempts: 1\n"
                                  "      stop_timeout_ms: 1000\n"
                                  "      idempotent: false\n"
                                  "      header_names: []\n"
                                  "      header_values: []\n";
static const char server_yaml[] = "version: 1\n"
                                  "adapters:\n"
                                  "  server:\n"
                                  "    kind: chttp.server\n"
                                  "    config:\n"
                                  "      schema_version: 1\n"
                                  "      poll_budget_ms: 1\n"
                                  "      tls_enabled: false\n"
                                  "      backend: " CHTTP_TEST_BACKEND "\n"
                                  "      network_connection_capacity: 4\n"
                                  "      network_command_capacity: 16\n"
                                  "      network_request_capacity: 16\n"
                                  "      network_completion_batch_capacity: 16\n"
                                  "      network_event_capacity: 16\n"
                                  "      network_max_send_bytes: 65536\n"
                                  "      network_receive_buffer_bytes: 4096\n"
                                  "      network_command_buffer_bytes: 131072\n"
                                  "      network_event_buffer_bytes: 65536\n"
                                  "      network_connect_timeout_ms: 1000\n"
                                  "      network_read_timeout_ms: 1000\n"
                                  "      network_write_timeout_ms: 1000\n"
                                  "      network_tls_handshake_timeout_ms: 0\n"
                                  "      network_tls_io_buffer_bytes: 0\n"
                                  "      tls_ca_file: \"\"\n"
                                  "      tls_ca_path: \"\"\n"
                                  "      tls_cert_file: \"\"\n"
                                  "      tls_key_file: \"\"\n"
                                  "      tls_key_password: \"\"\n"
                                  "      tls_alpn: []\n"
                                  "      protocol: \"h1\"\n"
                                  "      bind_host: \"127.0.0.1\"\n"
                                  "      bind_port: 0\n"
                                  "      path: \"/echo\"\n"
                                  "      tls_client_auth: \"none\"\n"
                                  "      backlog: 8\n"
                                  "      route_capacity: 1\n"
                                  "      middleware_capacity: 0\n"
                                  "      max_route_middleware_count: 0\n"
                                  "      max_route_param_count: 0\n"
                                  "      max_route_param_bytes: 0\n"
                                  "      max_target_bytes: 256\n"
                                  "      max_header_count: 16\n"
                                  "      max_header_bytes: 1024\n"
                                  "      max_request_body_bytes: 512\n"
                                  "      max_response_header_count: 16\n"
                                  "      max_response_header_bytes: 1024\n"
                                  "      max_response_body_bytes: 512\n"
                                  "      stream_chunk_bytes: 512\n"
                                  "      max_buffered_response_body_bytes: 512\n"
                                  "      buffer_capacity_bytes: 1048576\n"
                                  "      h2_stream_capacity: 0\n"
                                  "      h2_input_buffer_bytes: 0\n"
                                  "      h2_output_buffer_bytes: 0\n"
                                  "      h2_hpack_dynamic_table_bytes: 0\n"
                                  "      h2_max_settings_count: 0\n"
                                  "      poll_slice_ms: 1\n"
                                  "      first_message_id: 1\n"
                                  "      stop_timeout_ms: 1000\n"
                                  "      max_request_message_bytes: 8192\n"
                                  "      success_status: 200\n"
                                  "      overload_status: 429\n"
                                  "      unavailable_status: 503\n"
                                  "      graph_error_status: 500\n"
                                  "      method: \"POST\"\n"
                                  "      response_content_type: \"application/octet-stream\"\n"
                                  "      error_content_type: \"text/plain\"\n"
                                  "      graph_error_body: \"flow execution failed\"\n";
static const char websocket_yaml[] = "version: 1\n"
                                     "adapters:\n"
                                     "  websocket:\n"
                                     "    kind: chttp.websocket_server\n"
                                     "    config:\n"
                                     "      schema_version: 1\n"
                                     "      poll_budget_ms: 1\n"
                                     "      tls_enabled: false\n"
                                     "      backend: " CHTTP_TEST_BACKEND "\n"
                                     "      network_connection_capacity: 4\n"
                                     "      network_command_capacity: 16\n"
                                     "      network_request_capacity: 16\n"
                                     "      network_completion_batch_capacity: 16\n"
                                     "      network_event_capacity: 16\n"
                                     "      network_max_send_bytes: 65536\n"
                                     "      network_receive_buffer_bytes: 4096\n"
                                     "      network_command_buffer_bytes: 131072\n"
                                     "      network_event_buffer_bytes: 65536\n"
                                     "      network_connect_timeout_ms: 1000\n"
                                     "      network_read_timeout_ms: 1000\n"
                                     "      network_write_timeout_ms: 1000\n"
                                     "      network_tls_handshake_timeout_ms: 0\n"
                                     "      network_tls_io_buffer_bytes: 0\n"
                                     "      tls_ca_file: \"\"\n"
                                     "      tls_ca_path: \"\"\n"
                                     "      tls_cert_file: \"\"\n"
                                     "      tls_key_file: \"\"\n"
                                     "      tls_key_password: \"\"\n"
                                     "      tls_alpn: []\n"
                                     "      protocol: \"h1\"\n"
                                     "      bind_host: \"127.0.0.1\"\n"
                                     "      bind_port: 0\n"
                                     "      path: \"/echo\"\n"
                                     "      tls_client_auth: \"none\"\n"
                                     "      backlog: 8\n"
                                     "      route_capacity: 1\n"
                                     "      middleware_capacity: 0\n"
                                     "      max_route_middleware_count: 0\n"
                                     "      max_route_param_count: 0\n"
                                     "      max_route_param_bytes: 0\n"
                                     "      max_target_bytes: 256\n"
                                     "      max_header_count: 16\n"
                                     "      max_header_bytes: 1024\n"
                                     "      max_request_body_bytes: 512\n"
                                     "      max_response_header_count: 16\n"
                                     "      max_response_header_bytes: 1024\n"
                                     "      max_response_body_bytes: 512\n"
                                     "      stream_chunk_bytes: 512\n"
                                     "      max_buffered_response_body_bytes: 512\n"
                                     "      buffer_capacity_bytes: 1048576\n"
                                     "      h2_stream_capacity: 0\n"
                                     "      h2_input_buffer_bytes: 0\n"
                                     "      h2_output_buffer_bytes: 0\n"
                                     "      h2_hpack_dynamic_table_bytes: 0\n"
                                     "      h2_max_settings_count: 0\n"
                                     "      poll_slice_ms: 1\n"
                                     "      first_message_id: 1\n"
                                     "      stop_timeout_ms: 1000\n"
                                     "      subprotocol: \"\"\n"
                                     "      session_capacity: 4\n"
                                     "      frame_capacity: 8\n"
                                     "      max_frame_bytes: 512\n"
                                     "      max_message_bytes: 1024\n"
                                     "      max_buffered_input_bytes: 1024\n";
#endif
