worker_processes auto;
error_log /dev/stderr notice;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format flowie_http
        '$remote_addr [$time_local] "$request" $status $body_bytes_sent '
        'origin="$http_origin" fetch_site="$http_sec_fetch_site" '
        'content_type="$http_content_type" content_length="$http_content_length" '
        'request_length=$request_length referer="$http_referer" user_agent="$http_user_agent"';
    access_log /dev/stdout flowie_http;
    sendfile on;
    include /etc/flowie-nginx/generated/http.conf;
    include /etc/flowie-nginx/http.d/*.conf;
}
