allow_anonymous true
persistence false
max_topic_alias 10

listener 1883
protocol mqtt

listener 8883
protocol mqtt
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/server.pem
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2

listener 8083
protocol websockets

listener 8084
protocol websockets
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/server.pem
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2

