#include "turbo_flow_pgsql.h"

#include "flow_timer.h"
#include "fmt.h"
#include "libpq-fe.h"
#include "turbo_thread.h"

#include <errno.h>
#include <limits.h>
#include <stdatomic.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FLOW_PGSQL_OUTBOX_TABLE "turbo_flow_outbox"
#define FLOW_PGSQL_OUTBOX_CAPACITY_LOCK_SEED "607599061"
#define FLOW_PGSQL_OUTBOX_ROW_LOCK_SEED "607599065"

typedef struct flow_pgsql_outbox_adapter_s {
  tstr_t resource_uid;
  tstr_t resource_owner;
  tstr_t conninfo;
  tstr_t outbox_name;
  turbo_flow_pgsql_outbox_role_t role;
  size_t capacity;
  size_t max_payload_size;
  uint32_t poll_interval_ms;
  size_t claim_scan_limit;
  int create_table;
  PGconn *connection;
  PGcancel *cancel;
  turbo_mutex_t lock;
  int lock_initialized;
  tf_timer_t poll_wait;
  int poll_wait_initialized;
  turbo_thread_t thread;
  int thread_started;
  atomic_int started;
  atomic_int last_status;
  atomic_uint_fast64_t accepted;
  atomic_uint_fast64_t delivered;
  atomic_uint_fast64_t requeued;
  atomic_uint_fast64_t failures;
  turbo_flow_t *flow;
  tstr_t source_name;
} flow_pgsql_outbox_adapter_t;

static const turbo_flow_option_field_t FLOW_PGSQL_OUTBOX_FIELDS[] = {
    {"conninfo", TURBO_FLOW_OPTION_SECRET,
     TURBO_FLOW_OPTION_REQUIRED | TURBO_FLOW_OPTION_SECRET_VALUE, 0u, 0u, NULL, 0u},
    {"outbox_name", TURBO_FLOW_OPTION_STRING, TURBO_FLOW_OPTION_REQUIRED, 0u, 0u, NULL, 0u},
    {"capacity", TURBO_FLOW_OPTION_SIZE,
     TURBO_FLOW_OPTION_REQUIRED | TURBO_FLOW_OPTION_HAS_MIN | TURBO_FLOW_OPTION_HAS_MAX, 1u,
     TURBO_FLOW_PGSQL_OUTBOX_MAX_CAPACITY, NULL, 0u},
    {"max_payload_size", TURBO_FLOW_OPTION_SIZE,
     TURBO_FLOW_OPTION_REQUIRED | TURBO_FLOW_OPTION_HAS_MIN | TURBO_FLOW_OPTION_HAS_MAX, 1u,
     TURBO_FLOW_PGSQL_OUTBOX_MAX_PAYLOAD_SIZE, NULL, 0u},
    {"poll_interval_ms", TURBO_FLOW_OPTION_U32,
     TURBO_FLOW_OPTION_REQUIRED | TURBO_FLOW_OPTION_HAS_MIN, 1u, 0u, NULL, 0u},
    {"claim_scan_limit", TURBO_FLOW_OPTION_SIZE,
     TURBO_FLOW_OPTION_REQUIRED | TURBO_FLOW_OPTION_HAS_MIN | TURBO_FLOW_OPTION_HAS_MAX, 1u,
     TURBO_FLOW_PGSQL_OUTBOX_MAX_CLAIM_SCAN, NULL, 0u},
    {"create_table", TURBO_FLOW_OPTION_BOOL, TURBO_FLOW_OPTION_REQUIRED, 0u, 0u, NULL, 0u}};

static const turbo_flow_adapter_schema_t FLOW_PGSQL_OUTBOX_SINK_SCHEMA = {
    NULL,
    TURBO_FLOW_ADAPTER_KIND_POSTGRESQL,
    TURBO_FLOW_ADAPTER_SINK,
    TURBO_FLOW_ADAPTER_OUTPUT,
    FLOW_PGSQL_OUTBOX_FIELDS,
    sizeof(FLOW_PGSQL_OUTBOX_FIELDS) / sizeof(FLOW_PGSQL_OUTBOX_FIELDS[0])};

static const turbo_flow_adapter_schema_t FLOW_PGSQL_OUTBOX_SOURCE_SCHEMA = {
    NULL,
    TURBO_FLOW_ADAPTER_KIND_POSTGRESQL,
    TURBO_FLOW_ADAPTER_SOURCE,
    TURBO_FLOW_ADAPTER_INPUT,
    FLOW_PGSQL_OUTBOX_FIELDS,
    sizeof(FLOW_PGSQL_OUTBOX_FIELDS) / sizeof(FLOW_PGSQL_OUTBOX_FIELDS[0])};

static const char FLOW_PGSQL_OUTBOX_STATUS_SCHEMA_TEXT[] =
    "schema TurboFlowPostgreSqlOutboxResource [id(303), version(1)];\n"
    "message PostgreSqlOutboxStatus {\n"
    "  bool started;\n"
    "  uint32 role;\n"
    "  int32 last_status;\n"
    "  string accepted;\n"
    "  string delivered;\n"
    "  string requeued;\n"
    "  string failures;\n"
    "}\n";

static const turbo_flow_resource_schema_t FLOW_PGSQL_OUTBOX_STATUS_SCHEMA = {
    sizeof(turbo_flow_resource_schema_t),
    TURBO_FLOW_DOMAIN_BUFFER_PERSISTENCE,
    TURBO_FLOW_RESOURCE_STORAGE,
    TURBO_FLOW_RESOURCE_DOCUMENT_STATUS,
    TURBO_FLOW_RESOURCE_DOCUMENT_JSON,
    "TurboFlowPostgreSqlOutboxResource",
    "PostgreSqlOutboxStatus",
    303u,
    1u,
    FLOW_PGSQL_OUTBOX_STATUS_SCHEMA_TEXT};

static int flow_pgsql_outbox_result_status(PGresult *result, ExecStatusType expected) {
  if (!result) return TURBO_EIO;
  return PQresultStatus(result) == expected ? TURBO_OK : TURBO_EIO;
}

static int flow_pgsql_outbox_exec_simple(PGconn *connection, const char *sql,
                                         ExecStatusType expected) {
  PGresult *result;
  int rc;
  if (!connection || !sql) return TURBO_EINVAL;
  result = PQexec(connection, sql);
  rc = flow_pgsql_outbox_result_status(result, expected);
  if (result) PQclear(result);
  return rc;
}

static int flow_pgsql_outbox_schema_prepare(flow_pgsql_outbox_adapter_t *adapter) {
  static const char ddl[] =
      "CREATE TABLE IF NOT EXISTS " FLOW_PGSQL_OUTBOX_TABLE " ("
      "outbox_name text NOT NULL,"
      "id bigint GENERATED BY DEFAULT AS IDENTITY,"
      "payload bytea NOT NULL,"
      "created_at timestamptz NOT NULL DEFAULT clock_timestamp(),"
      "PRIMARY KEY(outbox_name,id));"
      "CREATE INDEX IF NOT EXISTS turbo_flow_outbox_pending_idx ON " FLOW_PGSQL_OUTBOX_TABLE
      "(outbox_name,id);";
  static const char validate[] =
      "SELECT outbox_name::text,id::text,payload::bytea FROM " FLOW_PGSQL_OUTBOX_TABLE " LIMIT 0";
  PGresult *result;
  int rc;
  if (!adapter || !adapter->connection) return TURBO_EINVAL;
  if (adapter->create_table) {
    rc = flow_pgsql_outbox_exec_simple(adapter->connection, ddl, PGRES_COMMAND_OK);
    if (rc != TURBO_OK) return rc;
  }
  result = PQexec(adapter->connection, validate);
  rc = flow_pgsql_outbox_result_status(result, PGRES_TUPLES_OK);
  if (rc == TURBO_OK && PQnfields(result) != 3) rc = TURBO_EPROTO;
  if (result) PQclear(result);
  return rc;
}

static int flow_pgsql_outbox_connect(flow_pgsql_outbox_adapter_t *adapter) {
  int rc;
  if (!adapter || adapter->connection) return TURBO_EINVAL;
  adapter->connection = PQconnectdb(adapter->conninfo);
  if (!adapter->connection || PQstatus(adapter->connection) != CONNECTION_OK) {
    if (adapter->connection) PQfinish(adapter->connection);
    adapter->connection = NULL;
    return TURBO_EIO;
  }
  adapter->cancel = PQgetCancel(adapter->connection);
  if (!adapter->cancel) {
    PQfinish(adapter->connection);
    adapter->connection = NULL;
    return TURBO_ENOMEM;
  }
  rc = flow_pgsql_outbox_schema_prepare(adapter);
  if (rc != TURBO_OK) {
    PQfreeCancel(adapter->cancel);
    adapter->cancel = NULL;
    PQfinish(adapter->connection);
    adapter->connection = NULL;
  }
  return rc;
}

static void flow_pgsql_outbox_disconnect(flow_pgsql_outbox_adapter_t *adapter) {
  if (!adapter) return;
  if (adapter->cancel) PQfreeCancel(adapter->cancel);
  adapter->cancel = NULL;
  if (adapter->connection) PQfinish(adapter->connection);
  adapter->connection = NULL;
}

static int flow_pgsql_outbox_parse_count(PGresult *result, size_t *out) {
  const char *value;
  char *end = NULL;
  unsigned long long converted;
  if (!result || !out || PQresultStatus(result) != PGRES_TUPLES_OK || PQntuples(result) != 1 ||
      PQnfields(result) != 1 || PQgetisnull(result, 0, 0))
    return TURBO_EPROTO;
  value = PQgetvalue(result, 0, 0);
  errno = 0;
  converted = strtoull(value, &end, 10);
  if (errno != 0 || !end || *end != '\0' || converted > SIZE_MAX) return TURBO_EPROTO;
  *out = (size_t)converted;
  return TURBO_OK;
}

static int flow_pgsql_outbox_sink_commit(flow_pgsql_outbox_adapter_t *adapter,
                                         const turbo_flow_msg_t *msg) {
  static const char capacity_lock[] =
      "SELECT pg_advisory_xact_lock(hashtextextended($1," FLOW_PGSQL_OUTBOX_CAPACITY_LOCK_SEED "))";
  static const char count_rows[] =
      "SELECT count(*)::text FROM " FLOW_PGSQL_OUTBOX_TABLE " WHERE outbox_name=$1";
  static const char insert_row[] =
      "INSERT INTO " FLOW_PGSQL_OUTBOX_TABLE "(outbox_name,payload) VALUES($1,$2::bytea)";
  const char *one_value[1] = {adapter->outbox_name};
  const char *insert_values[2];
  int insert_lengths[2] = {0, 0};
  int insert_formats[2] = {0, 1};
  PGresult *result = NULL;
  size_t depth = 0u;
  int rc;
  rc = flow_pgsql_outbox_exec_simple(adapter->connection, "BEGIN", PGRES_COMMAND_OK);
  if (rc != TURBO_OK) return rc;
  result = PQexecParams(adapter->connection, capacity_lock, 1, NULL, one_value, NULL, NULL, 0);
  rc = flow_pgsql_outbox_result_status(result, PGRES_TUPLES_OK);
  if (result) PQclear(result);
  if (rc != TURBO_OK) goto rollback;
  result = PQexecParams(adapter->connection, count_rows, 1, NULL, one_value, NULL, NULL, 0);
  rc = flow_pgsql_outbox_parse_count(result, &depth);
  if (result) PQclear(result);
  if (rc != TURBO_OK) goto rollback;
  if (depth >= adapter->capacity) {
    rc = TURBO_ENOSPC;
    goto rollback;
  }
  insert_values[0] = adapter->outbox_name;
  insert_values[1] = msg->payload.data ? msg->payload.data : "";
  insert_lengths[1] = (int)msg->payload.len;
  result = PQexecParams(adapter->connection, insert_row, 2, NULL, insert_values, insert_lengths,
                        insert_formats, 0);
  rc = flow_pgsql_outbox_result_status(result, PGRES_COMMAND_OK);
  if (result) PQclear(result);
  if (rc != TURBO_OK) goto rollback;
  rc = flow_pgsql_outbox_exec_simple(adapter->connection, "COMMIT", PGRES_COMMAND_OK);
  if (rc == TURBO_OK) return TURBO_OK;

rollback:
  (void)flow_pgsql_outbox_exec_simple(adapter->connection, "ROLLBACK", PGRES_COMMAND_OK);
  return rc;
}

static int flow_pgsql_outbox_lock_row(flow_pgsql_outbox_adapter_t *adapter, const char *row_id,
                                      int *locked) {
  static const char sql[] = "SELECT pg_try_advisory_lock(hashtextextended($1 || ':' || "
                            "$2," FLOW_PGSQL_OUTBOX_ROW_LOCK_SEED "))";
  const char *values[2] = {adapter->outbox_name, row_id};
  PGresult *result;
  int rc;
  if (!locked) return TURBO_EINVAL;
  *locked = 0;
  result = PQexecParams(adapter->connection, sql, 2, NULL, values, NULL, NULL, 0);
  rc = flow_pgsql_outbox_result_status(result, PGRES_TUPLES_OK);
  if (rc == TURBO_OK &&
      (PQntuples(result) != 1 || PQnfields(result) != 1 || PQgetisnull(result, 0, 0)))
    rc = TURBO_EPROTO;
  if (rc == TURBO_OK) {
    const char *value = PQgetvalue(result, 0, 0);
    if (strcmp(value, "t") == 0) *locked = 1;
    else if (strcmp(value, "f") != 0) rc = TURBO_EPROTO;
  }
  if (result) PQclear(result);
  return rc;
}

static int flow_pgsql_outbox_unlock_row(flow_pgsql_outbox_adapter_t *adapter, const char *row_id) {
  static const char sql[] =
      "SELECT pg_advisory_unlock(hashtextextended($1 || ':' || $2," FLOW_PGSQL_OUTBOX_ROW_LOCK_SEED
      "))";
  const char *values[2] = {adapter->outbox_name, row_id};
  PGresult *result;
  int rc;
  result = PQexecParams(adapter->connection, sql, 2, NULL, values, NULL, NULL, 0);
  rc = flow_pgsql_outbox_result_status(result, PGRES_TUPLES_OK);
  if (rc == TURBO_OK && (PQntuples(result) != 1 || PQnfields(result) != 1 ||
                         PQgetisnull(result, 0, 0) || strcmp(PQgetvalue(result, 0, 0), "t") != 0))
    rc = TURBO_EPROTO;
  if (result) PQclear(result);
  return rc;
}

static int flow_pgsql_outbox_claim(flow_pgsql_outbox_adapter_t *adapter, tstr_t *row_id,
                                   tstr_t *payload) {
  static const char candidates_sql[] = "SELECT id::text FROM " FLOW_PGSQL_OUTBOX_TABLE
                                       " WHERE outbox_name=$1 ORDER BY id LIMIT $2::integer";
  static const char payload_sql[] =
      "SELECT payload FROM " FLOW_PGSQL_OUTBOX_TABLE " WHERE outbox_name=$1 AND id=$2::bigint";
  char scan_limit[32];
  const char *candidate_values[2] = {adapter->outbox_name, scan_limit};
  PGresult *candidates = NULL;
  int written;
  int rc;
  if (!row_id || !payload || *row_id || *payload) return TURBO_EINVAL;
  written = snprintf(scan_limit, sizeof(scan_limit), "%zu", adapter->claim_scan_limit);
  if (written < 0 || (size_t)written >= sizeof(scan_limit)) return TURBO_ERANGE;
  candidates =
      PQexecParams(adapter->connection, candidates_sql, 2, NULL, candidate_values, NULL, NULL, 0);
  rc = flow_pgsql_outbox_result_status(candidates, PGRES_TUPLES_OK);
  if (rc != TURBO_OK) goto done;
  if (PQnfields(candidates) != 1) {
    rc = TURBO_EPROTO;
    goto done;
  }
  rc = TURBO_ENOENT;
  for (int row = 0; row < PQntuples(candidates); ++row) {
    const char *candidate_id;
    const char *payload_values[2];
    PGresult *selected = NULL;
    int locked = 0;
    if (PQgetisnull(candidates, row, 0)) {
      rc = TURBO_EPROTO;
      break;
    }
    candidate_id = PQgetvalue(candidates, row, 0);
    rc = flow_pgsql_outbox_lock_row(adapter, candidate_id, &locked);
    if (rc != TURBO_OK) break;
    if (!locked) {
      rc = TURBO_ENOENT;
      continue;
    }
    *row_id = tstr_dup(candidate_id);
    if (!*row_id) {
      (void)flow_pgsql_outbox_unlock_row(adapter, candidate_id);
      rc = TURBO_ENOMEM;
      break;
    }
    payload_values[0] = adapter->outbox_name;
    payload_values[1] = *row_id;
    selected =
        PQexecParams(adapter->connection, payload_sql, 2, NULL, payload_values, NULL, NULL, 1);
    rc = flow_pgsql_outbox_result_status(selected, PGRES_TUPLES_OK);
    if (rc == TURBO_OK &&
        (PQntuples(selected) != 1 || PQnfields(selected) != 1 || PQgetisnull(selected, 0, 0)))
      rc = PQntuples(selected) == 0 ? TURBO_ENOENT : TURBO_EPROTO;
    if (rc == TURBO_OK) {
      int payload_size = PQgetlength(selected, 0, 0);
      if (payload_size < 0 || (size_t)payload_size > adapter->max_payload_size) rc = TURBO_EMSGSIZE;
      else {
        *payload = tstr_new_len(PQgetvalue(selected, 0, 0), (size_t)payload_size);
        if (!*payload) rc = TURBO_ENOMEM;
      }
    }
    if (selected) PQclear(selected);
    if (rc == TURBO_OK) break;
    (void)flow_pgsql_outbox_unlock_row(adapter, *row_id);
    tstr_freep(row_id);
    if (rc != TURBO_ENOENT) break;
  }

done:
  if (candidates) PQclear(candidates);
  return rc;
}

static int flow_pgsql_outbox_delete(flow_pgsql_outbox_adapter_t *adapter, const char *row_id) {
  static const char sql[] =
      "DELETE FROM " FLOW_PGSQL_OUTBOX_TABLE " WHERE outbox_name=$1 AND id=$2::bigint";
  const char *values[2] = {adapter->outbox_name, row_id};
  PGresult *result;
  const char *affected;
  int rc;
  result = PQexecParams(adapter->connection, sql, 2, NULL, values, NULL, NULL, 0);
  rc = flow_pgsql_outbox_result_status(result, PGRES_COMMAND_OK);
  if (rc == TURBO_OK) {
    affected = PQcmdTuples(result);
    if (!affected || strcmp(affected, "1") != 0) rc = TURBO_EALREADY;
  }
  if (result) PQclear(result);
  return rc;
}

static int flow_pgsql_outbox_source_once(flow_pgsql_outbox_adapter_t *adapter) {
  turbo_flow_msg_t message;
  tstr_t row_id = NULL;
  tstr_t payload = NULL;
  int rc;
  int unlock_rc;
  rc = flow_pgsql_outbox_claim(adapter, &row_id, &payload);
  if (rc != TURBO_OK) return rc;
  turbo_flow_msg_init(&message);
  message.owned_payload = tstr_move(&payload);
  message.payload = tstr_to_v(message.owned_payload);
  rc = turbo_flow_publish(adapter->flow, adapter->source_name, &message);
  turbo_flow_msg_cleanup(&message);
  if (rc == TURBO_OK) rc = flow_pgsql_outbox_delete(adapter, row_id);
  else (void)atomic_fetch_add_explicit(&adapter->requeued, 1u, memory_order_relaxed);
  unlock_rc = flow_pgsql_outbox_unlock_row(adapter, row_id);
  tstr_freep(&row_id);
  if (rc == TURBO_OK && unlock_rc != TURBO_OK) rc = unlock_rc;
  if (rc == TURBO_OK)
    (void)atomic_fetch_add_explicit(&adapter->delivered, 1u, memory_order_relaxed);
  return rc;
}

static void flow_pgsql_outbox_source_thread(void *arg) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)arg;
  while (atomic_load_explicit(&adapter->started, memory_order_acquire) && adapter->flow &&
         turbo_flow_state(adapter->flow) != TURBO_FLOW_STATE_STARTED) {
    if (tf_timer_wait_for_ms(&adapter->poll_wait, 1u) == TURBO_ESHUTDOWN) return;
  }
  while (atomic_load_explicit(&adapter->started, memory_order_acquire)) {
    int rc = flow_pgsql_outbox_source_once(adapter);
    if (rc == TURBO_OK) continue;
    if (rc == TURBO_ENOENT) {
      if (tf_timer_wait_for_ms(&adapter->poll_wait, adapter->poll_interval_ms) == TURBO_ESHUTDOWN)
        break;
      continue;
    }
    atomic_store_explicit(&adapter->last_status, rc, memory_order_release);
    (void)atomic_fetch_add_explicit(&adapter->failures, 1u, memory_order_relaxed);
    atomic_store_explicit(&adapter->started, 0, memory_order_release);
    break;
  }
}

static int flow_pgsql_outbox_start(void *ctx, turbo_flow_t *flow,
                                   const turbo_flow_stage_plan_t *stage) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)ctx;
  int rc;
  if (!adapter || !flow || !stage ||
      ((adapter->role == TURBO_FLOW_PGSQL_OUTBOX_SOURCE) != (stage->is_source != 0)))
    return TURBO_EINVAL;
  turbo_mutex_lock(&adapter->lock);
  if (atomic_load_explicit(&adapter->started, memory_order_acquire) || adapter->connection) {
    turbo_mutex_unlock(&adapter->lock);
    return TURBO_EALREADY;
  }
  if (adapter->role == TURBO_FLOW_PGSQL_OUTBOX_SOURCE) {
    adapter->source_name = tstr_dup(stage->name);
    if (!adapter->source_name) {
      turbo_mutex_unlock(&adapter->lock);
      return TURBO_ENOMEM;
    }
    adapter->flow = flow;
  }
  rc = flow_pgsql_outbox_connect(adapter);
  if (rc != TURBO_OK) {
    tstr_freep(&adapter->source_name);
    adapter->flow = NULL;
    turbo_mutex_unlock(&adapter->lock);
    return rc;
  }
  tf_timer_reset(&adapter->poll_wait);
  atomic_store_explicit(&adapter->last_status, TURBO_OK, memory_order_release);
  atomic_store_explicit(&adapter->started, 1, memory_order_release);
  if (adapter->role == TURBO_FLOW_PGSQL_OUTBOX_SOURCE) {
    rc = turbo_thread_create(&adapter->thread, flow_pgsql_outbox_source_thread, adapter);
    if (rc != TURBO_OK) {
      atomic_store_explicit(&adapter->started, 0, memory_order_release);
      flow_pgsql_outbox_disconnect(adapter);
      tstr_freep(&adapter->source_name);
      adapter->flow = NULL;
      turbo_mutex_unlock(&adapter->lock);
      return rc;
    }
    adapter->thread_started = 1;
  }
  turbo_mutex_unlock(&adapter->lock);
  return TURBO_OK;
}

static int flow_pgsql_outbox_consume(void *ctx, turbo_flow_t *flow,
                                     const turbo_flow_stage_plan_t *stage, turbo_flow_msg_t *msg) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)ctx;
  const turbo_flow_protocol_settlement_envelope_t *settlement;
  int rc;
  (void)stage;
  if (!adapter || !flow || !msg || adapter->role != TURBO_FLOW_PGSQL_OUTBOX_SINK ||
      (msg->payload.len > 0u && !msg->payload.data) || msg->payload.len > INT_MAX)
    return TURBO_EINVAL;
  if (msg->payload.len > adapter->max_payload_size) return TURBO_EMSGSIZE;
  settlement = turbo_flow_msg_protocol_settlement(msg);
  if (settlement && (settlement->settled_point != 0u ||
                     settlement->requested_point != TURBO_FLOW_PROTOCOL_SETTLE_DURABLE))
    return TURBO_ENOTSUP;
  turbo_mutex_lock(&adapter->lock);
  if (!atomic_load_explicit(&adapter->started, memory_order_acquire) || !adapter->connection)
    rc = TURBO_ESHUTDOWN;
  else rc = flow_pgsql_outbox_sink_commit(adapter, msg);
  turbo_mutex_unlock(&adapter->lock);
  if (rc == TURBO_OK) {
    (void)atomic_fetch_add_explicit(&adapter->accepted, 1u, memory_order_relaxed);
    if (settlement) {
      const turbo_flow_protocol_route_t *route = turbo_flow_msg_protocol_route(msg);
      turbo_flow_protocol_settlement_request_t request =
          TURBO_FLOW_PROTOCOL_SETTLEMENT_REQUEST_INIT;
      if (!route) rc = TURBO_EPROTO;
      else {
        request.message = settlement->message;
        request.point = TURBO_FLOW_PROTOCOL_SETTLE_DURABLE;
        request.status = TURBO_OK;
        request.message_id = msg->id;
        request.attempt = msg->execution_attempt ? msg->execution_attempt : 1u;
        rc = turbo_flow_protocol_route_settle(flow, route, &request);
        if (rc == TURBO_OK) rc = turbo_flow_msg_complete_protocol_settlement(msg, request.point);
      }
    }
  }
  if (rc != TURBO_OK) {
    atomic_store_explicit(&adapter->last_status, rc, memory_order_release);
    (void)atomic_fetch_add_explicit(&adapter->failures, 1u, memory_order_relaxed);
  }
  return rc;
}

static void flow_pgsql_outbox_stop(void *ctx, turbo_flow_t *flow,
                                   const turbo_flow_stage_plan_t *stage) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)ctx;
  char cancel_error[256];
  (void)flow;
  (void)stage;
  if (!adapter) return;
  atomic_store_explicit(&adapter->started, 0, memory_order_release);
  if (adapter->poll_wait_initialized) tf_timer_stop(&adapter->poll_wait);
  if (adapter->thread_started && adapter->cancel)
    (void)PQcancel(adapter->cancel, cancel_error, (int)sizeof(cancel_error));
  if (adapter->thread_started) {
    (void)turbo_thread_join(&adapter->thread);
    adapter->thread_started = 0;
  }
  if (adapter->lock_initialized) turbo_mutex_lock(&adapter->lock);
  flow_pgsql_outbox_disconnect(adapter);
  adapter->flow = NULL;
  tstr_freep(&adapter->source_name);
  if (adapter->lock_initialized) turbo_mutex_unlock(&adapter->lock);
}

static int flow_pgsql_outbox_resource_metadata(void *ctx, turbo_flow_resource_metadata_t *out) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)ctx;
  int written;
  if (!adapter || !out || out->size < sizeof(*out)) return TURBO_EINVAL;
  *out = (turbo_flow_resource_metadata_t)TURBO_FLOW_RESOURCE_METADATA_INIT;
  out->domain = TURBO_FLOW_DOMAIN_BUFFER_PERSISTENCE;
  out->kind = TURBO_FLOW_RESOURCE_STORAGE;
  out->generation = 1u;
  out->observed_generation = 1u;
  written = snprintf(out->uid, sizeof(out->uid), "%s", adapter->resource_uid);
  if (written < 0 || (size_t)written >= sizeof(out->uid)) return TURBO_ENAMETOOLONG;
  written = snprintf(out->owner_name, sizeof(out->owner_name), "%s", adapter->resource_owner);
  return written < 0 || (size_t)written >= sizeof(out->owner_name) ? TURBO_ENAMETOOLONG : TURBO_OK;
}

static int flow_pgsql_outbox_resource_document(void *ctx,
                                               turbo_flow_resource_document_kind_t document_kind,
                                               turbo_flow_resource_document_t *out) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)ctx;
  turbo_flow_resource_metadata_t metadata = TURBO_FLOW_RESOURCE_METADATA_INIT;
  tstr_t payload;
  int rc;
  if (!adapter || !out || out->size < sizeof(*out)) return TURBO_EINVAL;
  if (document_kind != TURBO_FLOW_RESOURCE_DOCUMENT_STATUS) return TURBO_ENOTSUP;
  rc = flow_pgsql_outbox_resource_metadata(adapter, &metadata);
  if (rc != TURBO_OK) return rc;
  payload = tstr_format(
      "{\"started\":{},\"role\":{},\"last_status\":{},\"accepted\":\"{}\","
      "\"delivered\":\"{}\",\"requeued\":\"{}\",\"failures\":\"{}\"}",
      atomic_load_explicit(&adapter->started, memory_order_acquire) ? "true" : "false",
      (unsigned)adapter->role, atomic_load_explicit(&adapter->last_status, memory_order_acquire),
      atomic_load_explicit(&adapter->accepted, memory_order_relaxed),
      atomic_load_explicit(&adapter->delivered, memory_order_relaxed),
      atomic_load_explicit(&adapter->requeued, memory_order_relaxed),
      atomic_load_explicit(&adapter->failures, memory_order_relaxed));
  if (!payload) return TURBO_ENOMEM;
  rc = turbo_flow_resource_document_set_payload_copy(
      out, &metadata, &FLOW_PGSQL_OUTBOX_STATUS_SCHEMA, payload, tstr_len(payload));
  tstr_freep(&payload);
  return rc;
}

static void flow_pgsql_outbox_shutdown(void *ctx) {
  flow_pgsql_outbox_adapter_t *adapter = (flow_pgsql_outbox_adapter_t *)ctx;
  if (!adapter) return;
  flow_pgsql_outbox_stop(adapter, NULL, NULL);
  if (adapter->poll_wait_initialized) tf_timer_destroy(&adapter->poll_wait);
  if (adapter->lock_initialized) turbo_mutex_destroy(&adapter->lock);
  tstr_freep(&adapter->resource_uid);
  tstr_freep(&adapter->resource_owner);
  tstr_freep(&adapter->conninfo);
  tstr_freep(&adapter->outbox_name);
  free(adapter);
}

int turbo_flow_pgsql_register_outbox_adapter(turbo_flow_t *flow, const char *name,
                                             const turbo_flow_pgsql_outbox_config_t *config) {
  flow_pgsql_outbox_adapter_t *adapter;
  turbo_flow_adapter_ops_t ops;
  turbo_flow_resource_provider_registration_t resource =
      TURBO_FLOW_RESOURCE_PROVIDER_REGISTRATION_INIT;
  int rc;
  if (!flow || !name || !name[0] || !config || config->size < sizeof(*config) ||
      config->version != TURBO_FLOW_PGSQL_OUTBOX_API_VERSION ||
      (config->role != TURBO_FLOW_PGSQL_OUTBOX_SINK &&
       config->role != TURBO_FLOW_PGSQL_OUTBOX_SOURCE) ||
      !config->conninfo || !config->conninfo[0] || !config->outbox_name ||
      !config->outbox_name[0] || strlen(config->outbox_name) > TURBO_FLOW_PGSQL_OUTBOX_NAME_MAX ||
      config->capacity == 0u || config->capacity > TURBO_FLOW_PGSQL_OUTBOX_MAX_CAPACITY ||
      config->max_payload_size == 0u ||
      config->max_payload_size > TURBO_FLOW_PGSQL_OUTBOX_MAX_PAYLOAD_SIZE ||
      config->poll_interval_ms == 0u || config->claim_scan_limit == 0u ||
      config->claim_scan_limit > TURBO_FLOW_PGSQL_OUTBOX_MAX_CLAIM_SCAN ||
      (config->create_table != 0 && config->create_table != 1))
    return TURBO_EINVAL;
  adapter = (flow_pgsql_outbox_adapter_t *)calloc(1u, sizeof(*adapter));
  if (!adapter) return TURBO_ENOMEM;
  atomic_init(&adapter->started, 0);
  atomic_init(&adapter->last_status, TURBO_OK);
  atomic_init(&adapter->accepted, 0u);
  atomic_init(&adapter->delivered, 0u);
  atomic_init(&adapter->requeued, 0u);
  atomic_init(&adapter->failures, 0u);
  adapter->resource_uid = tstr_format("postgresql-outbox:{}", name);
  adapter->resource_owner = tstr_dup(name);
  adapter->conninfo = tstr_dup(config->conninfo);
  adapter->outbox_name = tstr_dup(config->outbox_name);
  adapter->role = config->role;
  adapter->capacity = config->capacity;
  adapter->max_payload_size = config->max_payload_size;
  adapter->poll_interval_ms = config->poll_interval_ms;
  adapter->claim_scan_limit = config->claim_scan_limit;
  adapter->create_table = config->create_table;
  if (!adapter->resource_uid || !adapter->resource_owner || !adapter->conninfo ||
      !adapter->outbox_name) {
    flow_pgsql_outbox_shutdown(adapter);
    return TURBO_ENOMEM;
  }
  if (tstr_len(adapter->resource_uid) > TURBO_FLOW_RESOURCE_UID_MAX ||
      tstr_len(adapter->resource_owner) > TURBO_FLOW_RESOURCE_OWNER_MAX) {
    flow_pgsql_outbox_shutdown(adapter);
    return TURBO_ENAMETOOLONG;
  }
  turbo_mutex_init(&adapter->lock);
  adapter->lock_initialized = 1;
  rc = tf_timer_init(&adapter->poll_wait);
  if (rc != TURBO_OK) {
    flow_pgsql_outbox_shutdown(adapter);
    return rc;
  }
  adapter->poll_wait_initialized = 1;
  memset(&ops, 0, sizeof(ops));
  ops.start = flow_pgsql_outbox_start;
  ops.consume = flow_pgsql_outbox_consume;
  ops.stop = flow_pgsql_outbox_stop;
  ops.shutdown = flow_pgsql_outbox_shutdown;
  resource.owner_name = name;
  resource.ops.metadata = flow_pgsql_outbox_resource_metadata;
  resource.ops.document = flow_pgsql_outbox_resource_document;
  resource.ctx = adapter;
  rc = turbo_flow_register_adapter_with_resources(flow, name, &ops, adapter,
                                                  config->role == TURBO_FLOW_PGSQL_OUTBOX_SOURCE
                                                      ? &FLOW_PGSQL_OUTBOX_SOURCE_SCHEMA
                                                      : &FLOW_PGSQL_OUTBOX_SINK_SCHEMA,
                                                  &resource, 1u);
  return rc;
}
