# MQTT-GATE-003: reject missing seeds, revision drift, failures, and monotonic resource growth.
if(NOT DEFINED EVIDENCE_FILE)
  message(FATAL_ERROR "EVIDENCE_FILE is required")
endif()
if(NOT EXISTS "${EVIDENCE_FILE}")
  message(FATAL_ERROR "nightly evidence is missing: ${EVIDENCE_FILE}")
endif()
file(READ "${EVIDENCE_FILE}" evidence)
string(JSON revision ERROR_VARIABLE revision_error GET "${evidence}" revision)
if(revision_error OR revision STREQUAL "")
  message(FATAL_ERROR "nightly evidence must contain a non-empty revision")
endif()
string(JSON record_count ERROR_VARIABLE count_error LENGTH "${evidence}" records)
if(count_error OR NOT record_count EQUAL 3)
  message(FATAL_ERROR "nightly evidence must contain corpus, soak and sanitizer records")
endif()
set(found_corpus 0)
set(found_soak 0)
set(found_sanitizer 0)
set(found_kinds)
math(EXPR last_record "${record_count} - 1")
foreach(index RANGE 0 ${last_record})
  string(JSON kind ERROR_VARIABLE kind_error GET "${evidence}" records ${index} kind)
  string(JSON record_revision ERROR_VARIABLE record_revision_error GET "${evidence}" records ${index} revision)
  string(JSON result ERROR_VARIABLE result_error GET "${evidence}" records ${index} result)
  string(JSON seed ERROR_VARIABLE seed_error GET "${evidence}" records ${index} seed)
  string(JSON monotonic_growth ERROR_VARIABLE growth_error GET "${evidence}" records ${index} resource_monotonic_growth)
  if(kind_error OR record_revision_error OR result_error OR seed_error OR growth_error)
    message(FATAL_ERROR "incomplete nightly evidence record at index ${index}")
  endif()
  if(NOT record_revision STREQUAL revision)
    message(FATAL_ERROR "nightly evidence revision mismatch for ${kind}")
  endif()
  if(NOT result STREQUAL "PASS" OR NOT seed MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "nightly ${kind} record lacks PASS result or seed")
  endif()
  if(monotonic_growth)
    message(FATAL_ERROR "nightly ${kind} reports monotonic resource growth")
  endif()
  list(FIND found_kinds "${kind}" duplicate_kind)
  if(NOT duplicate_kind EQUAL -1)
    message(FATAL_ERROR "nightly evidence contains duplicate ${kind} records")
  endif()
  list(APPEND found_kinds "${kind}")
  if(kind STREQUAL "corpus")
    set(found_corpus 1)
  elseif(kind STREQUAL "soak")
    set(found_soak 1)
  elseif(kind STREQUAL "sanitizer")
    string(JSON artifact_directory ERROR_VARIABLE artifact_error GET "${evidence}" records ${index}
                                                           artifact_directory)
    if(artifact_error OR artifact_directory STREQUAL "")
      message(FATAL_ERROR "nightly sanitizer record lacks artifact directory")
    endif()
    set(found_sanitizer 1)
  else()
    message(FATAL_ERROR "nightly evidence contains unknown record kind ${kind}")
  endif()
endforeach()
if(NOT found_corpus OR NOT found_soak OR NOT found_sanitizer)
  message(FATAL_ERROR "nightly evidence must include corpus, soak and sanitizer records")
endif()
message(STATUS "Nightly evidence verified for revision ${revision}")
