# MQTT-GATE-002: reject incomplete, failed, or ambiguous release evidence.
if(NOT DEFINED EVIDENCE_FILE)
  message(FATAL_ERROR "EVIDENCE_FILE is required")
endif()
if(NOT EXISTS "${EVIDENCE_FILE}")
  message(FATAL_ERROR "Flowie release evidence is missing: ${EVIDENCE_FILE}")
endif()
file(READ "${EVIDENCE_FILE}" evidence)
string(JSON revision ERROR_VARIABLE revision_error GET "${evidence}" revision)
if(revision_error OR revision STREQUAL "")
  message(FATAL_ERROR "release evidence must contain a non-empty revision")
endif()
string(JSON test_count ERROR_VARIABLE count_error LENGTH "${evidence}" tests)
if(count_error OR test_count EQUAL 0)
  message(FATAL_ERROR "release evidence has no test records")
endif()
set(required_names
    test_flowie_mqtt_protocol_matrix
    test_flowie_mqtt_protocol_corpus
    test_flowie_mqtt_client_fixed_interop
    flowie_mqtt_fixed_mqtt31_capability
    flowie_mqtt_fixed_mqtt31_ws_capability
    test_flowie_mosquitto_interop
    test_flowie_mosquitto_fixed_interop
    test_flowie_session_store_faults
    test_flowie_transport
    test_flowie_mqtt_endurance
    test_flowie_mqtt_soak
    flowie_server_check_redis_session_store
    flowie_server_check_https_auth_provider)
set(required_backends redis fixed)
set(found_names)
set(found_backends)
set(found_tls 0)
set(found_mtls 0)
math(EXPR last_test "${test_count} - 1")
foreach(index RANGE 0 ${last_test})
  string(JSON name ERROR_VARIABLE name_error GET "${evidence}" tests ${index} name)
  string(JSON result ERROR_VARIABLE result_error GET "${evidence}" tests ${index} result)
  string(JSON label ERROR_VARIABLE label_error GET "${evidence}" tests ${index} label)
  string(JSON backend ERROR_VARIABLE backend_error GET "${evidence}" tests ${index} backend)
  string(JSON version ERROR_VARIABLE version_error GET "${evidence}" tests ${index} version)
  string(JSON tls ERROR_VARIABLE tls_error GET "${evidence}" tests ${index} tls)
  if(name_error OR result_error OR label_error OR backend_error OR version_error OR tls_error)
    message(FATAL_ERROR "incomplete release evidence record at index ${index}")
  endif()
  if((name STREQUAL "flowie_mqtt_fixed_mqtt31_capability" OR
      name STREQUAL "flowie_mqtt_fixed_mqtt31_ws_capability") AND result STREQUAL "SKIP")
    message(STATUS "Optional MQTT 3.1 fixed-broker capability is not declared")
  elseif(NOT result STREQUAL "PASS")
    message(FATAL_ERROR "release evidence record ${name} is not PASS: ${result}")
  endif()
  if(NOT label MATCHES "(^|;)flowie-release(;|$)")
    message(FATAL_ERROR "release evidence record ${name} is missing flowie-release label")
  endif()
  list(FIND found_names "${name}" duplicate_name)
  if(NOT duplicate_name EQUAL -1)
    message(FATAL_ERROR "release evidence contains duplicate test ${name}")
  endif()
  list(APPEND found_names "${name}")
  list(APPEND found_backends "${backend}")
  if(tls MATCHES "TLS|WSS")
    set(found_tls 1)
  endif()
  if(tls MATCHES "mTLS")
    set(found_mtls 1)
  endif()
endforeach()
foreach(required IN LISTS required_names)
  list(FIND found_names "${required}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "release evidence is missing required test ${required}")
  endif()
endforeach()
foreach(required IN LISTS required_backends)
  list(FIND found_backends "${required}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "release evidence is missing backend ${required}")
  endif()
endforeach()
if(NOT found_tls)
  message(FATAL_ERROR "release evidence is missing real TLS/WSS evidence")
endif()
if(NOT found_mtls)
  message(FATAL_ERROR "release evidence is missing real mTLS evidence")
endif()
message(STATUS "Flowie release evidence verified for revision ${revision}")
